loadscript('public/js/config.js')
.load('public/js/paginator/paginator.js')
.load('public/js/initdb.js')
.load('public/js/mvp/mvp.js')
.load('public/js/models/mcreatepage.js')
.load('public/js/views/vcreatepage.js')
.load('public/js/presenters/pcreatepage.js')
.load('public/js/script.js')
.then(()=>console.log(`Scripts are loaded`))
.catch(console.error)
