loadscript('public/js/config.js')
.load('public/js/paginator/paginator.js')
.load('public/js/initdb.js')
.load('public/js/script.js')
.then(()=>console.log(`Scripts are loaded`))
.catch(console.error)
